### ISSUE TITLE
BE user story #6: Creating a flash card

### ISSUE THREAD

**Issue by B-gann21** [2201-DevPrep/DevPrep-FE#12]
When I send a POST request to `/api/v1/users/:user_id/cards`, with a JSON payload of the following format:
```
{
  "category": "technical",     <-- (or "behavioral")
  "front_side": "What is MVC?",
  "back_side": "stuff and things",     <-- (optional)
}
```
Then I should see this response with a status code of 201:
```
{
  "data": {
    "id": "1",
    "type": "flash_card",
    "attributes": {
      "category": "technical",
      "competence_rating": 0,
      "front_side": "what is MVC?",
      "back_side": "stuff and things",
      "user_id": "1"
    }
  }
}
```

If the `user_id` is not present, or not in the DB, i see this error with the status code 400:
```
{
  "error": "invalid user_id"
}
```

**Comment by Jeetch8** [comment]
Have you created the backend - please share the model or
Could you please share the API end point so that I can understand
